kafkaProperties:
  bootstrap.server: 'localhost:9092'
  client.id: 'consumer-client-id'
  schema.registry.url: 'http://localhost:8081'
topicProperties:
  name: 'avro-messages-section-5-2'
  numPartitions: 1
  replicationFactor: 1
  creationTimeoutSeconds: 10
consumerProperties:
  groupId: 'avro-messages-consumer-5-2-group-id'
  pollingTimeoutInMilliSeconds: 100